# Generated by Django 4.2.3 on 2023-07-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0002_alter_flow_reach_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesToVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=20, verbose_name='Form ID')),
                ('company_code', models.CharField(max_length=5, verbose_name='Company Code')),
                ('sold_to_BP', models.CharField(max_length=50, verbose_name='Sold To BP')),
                ('ship_to_BP', models.CharField(max_length=50, verbose_name='Ship To BP')),
                ('order_series', models.CharField(max_length=50, verbose_name='Order Series')),
                ('order_type', models.CharField(max_length=50, verbose_name='Order Type')),
                ('sales_office', models.CharField(max_length=50, verbose_name='Sales Office')),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('postal_add_code', models.CharField(max_length=200, verbose_name='Postal Address Code')),
                ('del_add_code', models.CharField(max_length=200, verbose_name='Delivery Address Code')),
                ('order_discount', models.CharField(max_length=50, verbose_name='Order Discount')),
                ('warehouse', models.CharField(max_length=50, verbose_name='Warehouse')),
                ('pricelist', models.CharField(max_length=50, verbose_name='Pricelist')),
                ('payment_terms', models.CharField(max_length=50, verbose_name='Payment Terms')),
                ('ref_A1', models.CharField(max_length=50, verbose_name='Reference A1')),
                ('ref_B1', models.CharField(max_length=50, verbose_name='Reference B1')),
                ('header_text', models.CharField(max_length=50, verbose_name='Header Text')),
                ('ext_sales_rep', models.CharField(max_length=50, verbose_name='External Sales Rep Code')),
                ('int_sales_rep', models.CharField(max_length=50, verbose_name='Internal Sales Rep code')),
                ('planned_del_date', models.DateField(verbose_name='Planned Delivery Date')),
                ('planned_reciept_date', models.DateField(verbose_name='Planned Receipt Date')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('IN_PROCESS', 'In Process'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], max_length=15, verbose_name='Form Status')),
                ('reach_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.flow')),
            ],
        ),
    ]
