# Generated by Django 4.2.3 on 2023-07-14 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0003_flowname_flow_abbr_alter_flowname_flow_name'),
        ('form', '0002_alter_salestovendor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=300, verbose_name='Remarks')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], max_length=20, verbose_name='Actions')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date time of remark')),
                ('form_id', models.CharField(max_length=20, verbose_name='Form ID')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flowname')),
            ],
        ),
    ]
