# Generated by Django 4.2.3 on 2023-07-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.TextField(max_length=200, verbose_name='name of flow')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach_code', models.IntegerField(verbose_name='reach code')),
                ('flow_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flow.flowname')),
                ('pending_at_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.role', verbose_name='Pending at role')),
            ],
        ),
    ]
