# Generated by Django 4.2.3 on 2023-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_flowname_flow_abbr_alter_flowname_flow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowname',
            name='flow_abbr',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Flow Name Abbreviation'),
        ),
    ]
